### ISSUE TITLE
Whitespace control

### ISSUE THREAD

**Issue by fantoine** [Keats/tera#149]
I'm looking for a way to handle whitespace correctly on generated content, since I use Tera to generate non-HTML content.

Jinja implements [whitespace control](http://jinja.pocoo.org/docs/dev/templates/#whitespace-control) which make it possible to precisely specify whitespaces management.

Do you plan to include this kind of feature?

**Comment by Keats** [comment]
Tera tries to do the "clean" (trim_blocks and lstrip_blocks in Jinja2) behaviour automatically, even though it still fails at some places.

For the whitespace handling with `{%-` and `-%}`, I don't think I'll implement it myself but I would welcome a PR for it

**Comment by Keats** [comment]
Fixed as of 0.11.0-beta, stable release will come once `pest` releases 1.0

**Comment by rootkea** [comment]
> Tera tries to do the "clean" (trim_blocks and lstrip_blocks in Jinja2) behaviour automatically.

This is so logical and I completely agree with this behavior. Have things changed since?

```
<div>
    {% if True %}
        yay
    {% endif %}
</div>
```

I get:
```
<div>
    
        yay
    
</div>
```

I expected no blank lines in place of `if` block statements.

Honestly, it puzzles why would someone want to print blank lines in place of non-printing statements like `if` or `set` by default. And then using constructs to eliminate those (unnecessary) blank lines. It should be opposite like you have stated. By default no blank lines in place of non-printing statements and give construct to print blank line if someone desires.

**Comment by rootkea** [comment]
Case in point: An example from Tera documentation: https://tera.netlify.app/docs/#whitespace-control

```
{% set my_var = 2 %}
{{ my_var }}
```

Why would I want `set` statement (whose only objective is to set variable to a value) to print a newline? I just don't get it. And then use constructs to delete those irrational blank lines.

The user just wanted  to set `my_var` to 2 and then print the variable. if she wants to print a blank line before or after printing `my_var` then she simply can use `Enter` (newline) in template source and it gets rendered as a blank line. Very straightforward and simple. You can even provide an explicit statement to print newline (though I don't see why as simple `Enter` works) but why to print newlines by for non-printing statements?

**Comment by Keats** [comment]
Many things have changed since 2017 haha.
It will probably default for the clean approach for Tera v2 though, I had completely forgotten about that, thanks for the reminder
