### ISSUE TITLE
Cannot import macros inside if blocks

### ISSUE THREAD

**Issue by Lirusaito** [Keats/tera#256]
I have a file, let's call it index.html.tera, that has
```jinja
Stuff
{% if user %}
stuff here
{% import "test" as test %}
{{ test::test() }}
other stuff here
{% endif %}
more stuff
```
Macro contents don't matter for the issue, but here they are:
whatever.html.tera contains the following:
```jinja
{% import "test_macro" as test %}
{{ test::test() }}
```
and that is, of course
```jinja
{% macro test() %}
TEST SUCCESS
{% endmacro test %}
```

This will result in this error:
```rust
=> Error: Failed to render 'index': error while rendering a macro from the `test` namespace
=> Error: Macro `test` was not found in the namespace `test`
```

The issue is apparently here:
```jinja
{% if user %}
{% import "test" as test %}
{{ test::test() }}
{% endif %}
```
And it can be fixed by doing this:
```jinja
{% import "test" as test %}
{% if user %}
{{ test::test() }}
{% endif %}
```

I can, of course, just fix all these(probably import at the tops of files), unless the old behavior is desirable and you'd like to fix it so it will work.

**Comment by Keats** [comment]
That is not limited to `if` blocks.
A Tera templates only currently looks for an `import` at the top level of a template, like `include` or a macro definition but can currently be used anywhere inside a template.

Since loading macros is fairly cheap (a couple of hashmap insertion), it should be required in the grammar to be at the same level as an `include`. This is a breaking change in theory so that will be fixed in the next major version.
