### ISSUE TITLE
rust format & clippy

### ISSUE THREAD

**Issue by bootandy** [Keats/tera#270]
Can we run rust format (and later start to run clippy) on this project?

I ran cargo fmt on a local branch and pushed it here but it has a truly terrifying number of differences. 

https://github.com/bootandy/tera/tree/fix_multi_bracket

Is your plan to wait until rust format & cargo move into stable before using them? Is there anything stopping us from adding rust format now?

**Comment by Keats** [comment]
I did try rustfmt recently: https://github.com/Keats/tera/pull/259 however there are too many places where the resulting formatting is bad like these: https://github.com/Keats/tera/pull/259/files#diff-7afbb7fb9361f816954d9abfc961a143R124 , https://github.com/Keats/tera/pull/259/files#diff-6fe7bf1bf33480c21cdaaf564b756992R140 or https://github.com/Keats/tera/pull/259/files#diff-93bf1de92d8ca0ef979de6276e8e5d77R36
I raised a couple of issues about the bad formatting but those are apparently intentional.

Clippy is run quite frequently on the repo, I believe the vast majority of the warnings are coming from the filter/tests type definition. There's also the complexity of the whitespace handling function but I didn't manage to get that down

**Comment by bootandy** [comment]
I agree that rust format is making some bad formatting choices. 

Generally I think it is good to have a style build that checks formatting. 

Perhaps we should start using the: #[cfg_attr(rustfmt, rustfmt_skip)]  on parts of the code that it is styling badly, then we could run format on the rest of it ?

**Comment by Keats** [comment]
> Perhaps we should start using the: #[cfg_attr(rustfmt, rustfmt_skip)] on parts of the code that it is styling badly, then we could run format on the rest of it ?

I feel like this is going to be very annoying to do. It's probably simpler to run the latest rustfmt on a branch, push that branch on Github, open the diff viewer and do the changes manually or checkout files from the rustfmt'd branch if we are happy with a file in particular. I'll do that today for all the non-controversial changes

**Comment by Keats** [comment]
Formatting is at https://github.com/Keats/tera/pull/271
If you want to tackle some of the clippy lints, feel free although I don't think the filter/testers need to have their type changed to take references.

**Comment by bootandy** [comment]
I understand that adding #[cfg_attr...] could get annoying if there were many.

How about adding a rustfmt.toml to not apply some of the more frustrating style rules?
https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md

I'm trying to work towards getting a more consistent styling and I believe its better to apply say 90% of the rules all the time than sporadically attempting to apply all of them. 

(Also by default I apply rustfmt on file save so I turn that off when I'm looking at Tera, and I'm worried I broke a clippy rule with one of my commits :-) ).

Happy to take a look at the above once 271 is merged - I'm curious to know what is left.

**Comment by Keats** [comment]
> How about adding a rustfmt.toml to not apply some of the more frustrating style rules?

I would be ok with it if we can identify the right rules. The current rustfmt behaviour feels very random to me: in Tera it asked me to alwais turn the one-liner `let my_var = if condition { a } else { b }` into a multiline

```
let my_var = if condition {
    a 
} else {
    b
};
```
however long the line was but I ran the same version of rustfmt on another repository and it asked me to do the opposite.
Not to mention rustfmt asking me to break up a 85 chars line but not saying anything about the 110 chars line right below
