### ISSUE TITLE
Change filters & testers signature

### ISSUE THREAD

**Issue by Keats** [Keats/tera#328]
To take borrowed arguments, not values.
The current state forces to clone the arguments before passing them, which is wasteful especially for testers.

**Comment by Keats** [comment]
The global fn signature could also maybe return a `Cow` to avoid some cloning?

**Comment by rjsberry** [comment]
Is there a reason why `FilterFn` and `TestFn` are both fn pointers rather than boxed trait objects (like `GlobalFn`)? I.e.:

```rust
type FilterFn = Box<dyn Fn(&Value, &HashMap<String, Value>) -> Result<Value> + Send + Sync>;

type TesterFn = Box<dyn Fn(&Option<Value>, &Vec<Value>) -> Result<bool> + Send + Sync>;
```

I use builders to dynamically create global functions (much like the docs [example](https://tera.netlify.com/docs/templates/#functions))  but this can't be done for tests/filters.

**Comment by Keats** [comment]
Have a look at the `v1` branch, they are now traits like https://github.com/Keats/tera/blob/v1/src/builtins/filters/mod.rs#L13-L17
