### ISSUE TITLE
What is the easiest way to concatenate lists in template?

### ISSUE THREAD

**Issue by matklad** [Keats/tera#347]
Hi!

What would be "the official" way to iterate over `xs + ys` in template?

Currently I use `{% for kw in concat(a=keywords, b=contextual_keywords) %}` where `concat` is defined as 

```
fn concat(args: HashMap<String, tera::Value>) -> tera::Result<tera::Value> {
    let mut elements = Vec::new();
    for &key in ["a", "b", "c"].iter() {
        let val = match args.get(key) {
            Some(val) => val,
            None => continue,
        };
        let val = val.as_array().unwrap();
        elements.extend(val.iter().cloned());
    }
    Ok(tera::Value::Array(elements))
}
```

and that is rather painful to look at :)

Is there a better way?

**Comment by Keats** [comment]
Currently there is no array concatenation support, only strings/numbers.

I'm not entirely sure how array concatenations would look like if it was directly supported in Tera :/ String concatenation use `~` but it would be confusing to use the same for arrays I think.
Any ideas?

**Comment by matklad** [comment]
I have tried a custom **filter**, `{% for kw in [keywords, contextual_keywords] | flatten %}`, but that unfortunately is invalid syntax.

**Comment by Keats** [comment]
I didn't really allow much with the array syntax in the grammar currently.

The main things we want to do with an array are:

- pushing an element into an array
- concatenating with another array

The rest (iterating, reversing etc) is already in place.

Pushing and concatenating could use the same syntax, but using `+` or `~` would be a bit weird since it would hijack a math expression or a string concatenation. At the same time, using a new made up symbol would be super weird. Not sure what to do!

**Comment by matklad** [comment]
Also, just to be clear, I don't argue that terra needs to have concatenation build-in: django templates don't have it, and I need it for a rather specific use-case. However it'd be cool if I could define my own concatenation without `for &key in ["a", "b", "c"].iter() ` hack. So perhaps just supporting positional arguments in functions will be enough?

**Comment by matklad** [comment]
Looks like Jinja overloads `+`:

> `+`   Adds two objects together. Usually the objects are numbers, but if both are strings or lists, you can concatenate them this way. This, however, is not the preferred way to concatenate strings! For string concatenation, have a look-see at the ~ operator. {{ 1 + 1 }} is 2.

>a_string + an_array would result in a string or an error and an_array + a_string would be pushing the string into an array?

My first though is that `x + y` should be an error if type(x) != type(y). I haven't worked with template engines a lot and, given that they in general tend to render missing values as empty strings, instead of bailing with an error, perhaps a more lax typing discipline is better?

OTOH, we starting strict and relaxing later is backward-combatible.

**Comment by Keats** [comment]
> My first though is that x + y should be an error if type(x) != type(y)

But for example I just added `x ~ y` where x = String and y = Number because concatenating strings and number is a fairly common operation, for example in Gutenberg doing `pagination_root ~ page_number`.

> in general tend to render missing values as empty strings, instead of bailing with an error, perhaps a more lax typing discipline is better?

I had a mode like that at some point but it was pretty frustrating to use when you made a typo compared to the current mode and I do miss it when I am writing some Django templates to be honest...

For concatenation, I think it could make sense as a filter so in your case, it would be `{% for kw in keywords | concat(with=contextual_keywords) %}` as I don't think it makes sense to have a specific symbol for it. It definitely isn't super pretty though.

Overriding `+` doesn't work here I think, would `list_a + list_b` concatenate the lists or push `list_b` into `list_a`? If we take `list_a = [1, 2]` and `list_b = [3]`,

- in JavaScript, it obviously outputs the stringified version `1,23`. Why not
- in Python/Ruby it concats the vaues of b into a
- in Rust/Go it errors with `binary operation `+` cannot be applied to type `std::vec::Vec<{integer}>`

I'm not too sure what's happening for `an_int + a_list`. Does it push the int at index 0? Is it an error?

Liquid seems to use a filter as well: https://shopify.github.io/liquid/filters/concat/

**Comment by Keats** [comment]
I think I'll go with a concat filter for now. It could also be used for pushing a value to be honest..

**Comment by Keats** [comment]
I have added the `concat` filter in the `next` branch so you can now do things like `{% for kw in keywords | concat(with=contextual_keywords) %}`.
Does that fit your needs or do you need more array literal support in the grammar itself?

**Comment by matklad** [comment]
>Does that fit your needs or do you need more array literal support in the grammar itself?

If `xs | concat(with=a) | concat(with=b)` works (and it should, I guess?) then I don't need anything else.

**Comment by Keats** [comment]
It should work yes, try with the `next` branch when you have time and I'll push a release if it's working.

**Comment by Keats** [comment]
@matklad a little ping, to make sure I release something that works for you and don't need to have breaking changes later :)

**Comment by matklad** [comment]
Tested just now, and it works.

I still have doubts that maybe overloading `+` for collections makes sense, but I guess we can always add it later.

**Comment by Keats** [comment]
Thanks!

> I still have doubts that maybe overloading + for collections makes sense, but I guess we can always add it later.

It's not ruled off completely, just that I don't think it's going to happen in 1.0 as the list for v1 release is already pretty long

**Comment by Keats** [comment]
It's in 0.11.19!
