### ISSUE TITLE
Tera::register_filter doc references undefined make_filter_fn

### ISSUE THREAD

**Issue by CAD97** [Keats/tera#455]
For `@1.0.0-beta.16`, here is one potential definition:

```rust
fn make_filter_fn<'a, T: Into<Value> + serde::de::DeserializeOwned>(
    name: &'a str,
    f: impl Fn(T) -> T + Sync + Send + 'a,
) -> impl tera::Filter + 'a {
    move |value: &Value, _: &HashMap<String, Value>| -> tera::Result<Value> {
        let val = tera::try_get_value!(name, "value", T, value);
        Ok(f(val).into())
    }
}
```

Example usage:

```rust
tera.register_filter(
    "camel_case",
    make_filter_fn("camel_case", |s: String| s.to_camel_case()),
);
```

It's unfortunate that the name has to be specified twice, but I don't think it's practical to overload `Tera::register_filter` to accept both `(&Value, &HashMap) -> Result<Value>` and `for<T: Into<Value> + DeserializeOwned> (T) -> T`.

**Comment by Keats** [comment]
I believe `make_filter_fn` was used in some older beta version but it got completely removed. Looks like the docs need to be updated to remove its mention. I'm not sure about adding it since there is a default impl for Fn and you can just call `register_filter("camel_case", camel_case)` where `camel_case` is a function of `(value: &Value, _: &HashMap<String, Value>) -> Result<Value>` type

**Comment by CAD97** [comment]
It can still be useful to do the `Value`/concrete type dance automatically, but I can definitely see where it might not be useful enough to warrant inclusion.
