### ISSUE TITLE
URLs in HashMap keys results in "Failed to render"

### ISSUE THREAD

**Issue by joepio** [Keats/tera#590]
First off: thanks for making & maintaining this! Love it :)

It seems like the square bracket syntax does not support (some of the characters in) URLs.

```rust
    let mut tera_context = tera::Context::new();
    let mut map= HashMap::new();
    map.insert("https://example.com/url", "url value, not working");
    map.insert("simplekey", "simple key value, working");
    tera_context.insert("map", &map);
```

```
    {{ map["simplekey"] }} => works fine 
    {{ map["https://example.com/url"]}} => "Failed to render \'map_example.html\'" 
```

It took me a while to find the cause of this issue - the error wasn't clear. (but error handling isn't what this issue is about)

**Comment by Keats** [comment]
I think that's because the map key in the parser doesn't support characters like `:` or `/` maybe? A bit weird and shouldn't be too hard to fix if it's that.

**Comment by MathiasPius** [comment]
I did a few tests, and it's actually the `.` that's the problem.

The map index is interpreted as a JSON Pointer into the context when rendered, but the dot is not escaped (since it is valid JSON Pointer notation), which means that `map["https://example.com"]` actually performs a lookup against `map["https://example"].com`.

It appears that serde (probably in accordance with the json spec) makes no distinction between `{ "google.com": 3 }` and  `{ "google": { "com": 3} }`, but I don't know for sure.

It would appear to be a general issue with any string containing dots.

Here's the test I used:
```rs
#[test]
fn test_render_map_with_complex_key() {
    let mut my_tera = Tera::default();
    my_tera
        .add_raw_template("test", r#"{{ map["a.b.c"] }}"#)
        .unwrap();

    let mut map= HashMap::new();
    map.insert("a.b.c", "success");

    let mut tera_context = Context::new();
    tera_context.insert("map", &map);

    my_tera.render("test", &tera_context).unwrap();
}
```
