### ISSUE TITLE
Cannot extends template file while that file is not registered.

### ISSUE THREAD

**Issue by suraw00t** [Keats/tera#942]
```
{# account/signup.html #}
{% extends "base/base.html" %}
...
```
Error because base/base.html is not registered before extends by another

![image](https://github.com/user-attachments/assets/02873b4e-7e2b-4ec1-b0f7-2792c7d7f206)

How can I use this [initialize_template()](https://github.com/suraw00t/rsblog/blob/de5929d78d8f705b9d69e26a5b790232419f6ab5/src/app/mod.rs#L41) for register templates from whole directory.

I try rename from account/ to zaccount/ it works fine. How can I solve this?
Or makes validating template file on rendering instead of on registering?

![image](https://github.com/user-attachments/assets/b5abdae7-d417-4cd3-a1e9-491c80c11bc0)

**Comment by Keats** [comment]
The easiest is to use `Tera::new` with the a glob. Otherwise use that same function to fetch a list of (tpl_name, tpl_content) and register them once with https://docs.rs/tera/latest/tera/struct.Tera.html#method.add_raw_templates (or https://docs.rs/tera/latest/tera/struct.Tera.html#method.add_template_files if you want Tera to load the files)

**Comment by suraw00t** [comment]
Thanks for information. It's very good.
